export const TOKEN_KEY = 'token'
export const ROLES_KEY = 'roles'
export const LOCALE_KEY = 'local_lang'
export const DEFAULT_LANG = 'zh_cn'
export const TIMEOUT_KEY = 'system_auto_time_by_minutes'
export const LAST_ACTIVE_KEY = 'last_active_time'
export const IS_TIMEOUT = 'is_timeout'
export const NOT_LOGIN = 'not_login'
