export const CMS_DASHBOARD = '/cms/dashboard'
export const CMS_SYSTEM = '/cms/system'
export const CMS_ADMIN = '/cms/admin'
export const CMS_ADMIN_ADD = '/cms/admin/add'
export const CMS_ADMIN_LIST = '/cms/admin/list'
export const CMS_LOGIN = '/login'
export const CMS_LOGOUT = '/logout'
